name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies via Homebrew
      run: |
        brew update
        brew install cmake ninja vulkan-headers vulkan-loader spirv-tools

    - name: Install SPIRV-LLVM-Translator
      run: |
        brew install llvm
    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_C_COMPILER=clang

    - name: Build Project
      run: cmake --build build --config Release
